ALTER TABLE doctors ADD COLUMN IF NOT EXISTS first_name TEXT;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS last_name TEXT;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS cpf TEXT;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS crm TEXT;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS crm_uf TEXT;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS memed_token TEXT;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS memed_id TEXT;

CREATE TABLE IF NOT EXISTS memed_cidades (
  id SERIAL PRIMARY KEY,
  nome TEXT NOT NULL,
  uf TEXT NOT NULL,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS memed_especialidades (
  id SERIAL PRIMARY KEY,
  nome TEXT NOT NULL,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
