CREATE TABLE IF NOT EXISTS memed_cidades (
  id SERIAL PRIMARY KEY,
  nome TEXT NOT NULL,
  uf TEXT NOT NULL,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS memed_especialidades (
  id SERIAL PRIMARY KEY,
  nome TEXT NOT NULL,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
