ALTER TABLE estoque_entradas
  ADD COLUMN IF NOT EXISTS lote VARCHAR(200),
  ADD COLUMN IF NOT EXISTS validade DATE;

ALTER TABLE estoque_saidas
  ADD COLUMN IF NOT EXISTS lote VARCHAR(200),
  ADD COLUMN IF NOT EXISTS validade DATE;
